# Generated by Django 5.2.15 on 2026-06-04 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(blank=True, max_length=120, verbose_name='Номер/маркировка коробки')),
                ('note', models.TextField(blank=True, verbose_name='Примечание по коробке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Коробка доставки',
                'verbose_name_plural': 'Коробки доставки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CourierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название доставки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('expected', 'Ожидается'), ('received', 'Принята'), ('assembling', 'Собирается к отправке'), ('ready', 'Готова к отправке'), ('shipped', 'Отправлена'), ('done', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='expected', max_length=24, verbose_name='Состояние доставки')),
                ('expected_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Ожидаемая дата приезда')),
                ('received_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата приёмки')),
                ('dispatch_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата сборки/отправки')),
                ('dispatch_time', models.TimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('courier_name', models.CharField(blank=True, max_length=255, verbose_name='Курьер / служба')),
                ('tracking_number', models.CharField(blank=True, max_length=255, verbose_name='Трек-номер / накладная')),
                ('sender', models.CharField(blank=True, max_length=255, verbose_name='Откуда / отправитель')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Куда / получатель')),
                ('storage_place', models.CharField(blank=True, max_length=255, verbose_name='Место хранения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курьерская доставка',
                'verbose_name_plural': 'Курьерские доставки',
                'ordering': ['expected_date', 'dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата')),
                ('text', models.TextField(blank=True, verbose_name='Заметка дня')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заметка дня',
                'verbose_name_plural': 'Заметки дней',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OneCImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='onec_imports/%Y/%m/%d/', verbose_name='Файл выгрузки 1С')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('done', 'Загружено'), ('failed', 'Ошибка')], db_index=True, default='processing', max_length=24)),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('rows_created', models.PositiveIntegerField(default=0, verbose_name='Добавлено')),
                ('rows_skipped_duplicates', models.PositiveIntegerField(default=0, verbose_name='Дубликатов пропущено')),
                ('rows_invalid', models.PositiveIntegerField(default=0, verbose_name='Ошибочных строк')),
                ('invalid_rows_preview', models.JSONField(blank=True, default=list, verbose_name='Первые ошибки')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка импорта')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Импорт 1С',
                'verbose_name_plural': 'Импорты 1С',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Поручение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'Начато'), ('done', 'Выполнено')], db_index=True, default='not_started', max_length=20, verbose_name='Статус')),
                ('planned_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата')),
                ('planned_time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['planned_date', 'planned_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Номер заявки/счёта должен быть в формате В3-00516/26: буква, цифра, дефис, 5 цифр, слэш, 2 цифры.', regex='^[A-ZА-ЯЁ]\\d-\\d{5}/\\d{2}$')], verbose_name='Номер заявки/счёта')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка/счёт',
                'verbose_name_plural': 'Заявки/счета',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CourierBoxAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courier_box_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.courierbox')),
            ],
            options={
                'verbose_name': 'Вложение коробки',
                'verbose_name_plural': 'Вложения коробок',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.courierdelivery')),
            ],
            options={
                'verbose_name': 'Комментарий доставки',
                'verbose_name_plural': 'Комментарии доставок',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='courierbox',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='api.courierdelivery'),
        ),
        migrations.CreateModel(
            name='CourierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courier_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.courierdelivery')),
            ],
            options={
                'verbose_name': 'Вложение доставки',
                'verbose_name_plural': 'Вложения доставок',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.task')),
            ],
            options={
                'verbose_name': 'Вложение задачи',
                'verbose_name_plural': 'Вложения задач',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.task')),
            ],
            options={
                'verbose_name': 'Комментарий задачи',
                'verbose_name_plural': 'Комментарии задач',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='api.workrequest', verbose_name='Связанные заявки/счета'),
        ),
        migrations.AddField(
            model_name='courierbox',
            name='requests',
            field=models.ManyToManyField(related_name='courier_boxes', to='api.workrequest', verbose_name='Счета/заявки в коробке'),
        ),
        migrations.CreateModel(
            name='OneCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField(db_index=True, verbose_name='Дата события')),
                ('invoice_raw', models.CharField(max_length=512, verbose_name='Счёт исходный')),
                ('invoice_number', models.CharField(db_index=True, max_length=32, verbose_name='Номер счёта')),
                ('invoice_prefix', models.CharField(db_index=True, max_length=8, verbose_name='Префикс счёта')),
                ('is_own_lab', models.BooleanField(db_index=True, default=False, verbose_name='Выполняется в нашей лаборатории')),
                ('counterparty', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Контрагент')),
                ('consignee', models.CharField(blank=True, max_length=512, verbose_name='Грузополучатель')),
                ('service_name', models.TextField(blank=True, verbose_name='Услуга')),
                ('work_description', models.TextField(blank=True, verbose_name='Описание работ / прибор')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Количество')),
                ('status_raw', models.CharField(db_index=True, max_length=512, verbose_name='Статус исходный')),
                ('status_code', models.CharField(choices=[('accepted_warehouse', 'Принято на склад БП/СП'), ('transferred_to_lab', 'Передано в лабораторию'), ('transferred_from_lab', 'Передано из лаборатории'), ('accepted_lab', 'Принято в лаборатории'), ('done_ready', 'Выполнено / готово к выдаче'), ('issued_customer', 'Выдан заказчику'), ('other', 'Другой статус')], db_index=True, default='other', max_length=32)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Штрихкод')),
                ('responsible_full_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ФИО ответственного')),
                ('instrument_key', models.CharField(db_index=True, max_length=512, verbose_name='Ключ прибора')),
                ('dedupe_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Хэш антидубля')),
                ('source_row_number', models.PositiveIntegerField(default=0, verbose_name='Строка исходного файла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.onecimportbatch')),
            ],
            options={
                'verbose_name': 'Событие 1С',
                'verbose_name_plural': 'События 1С',
                'ordering': ['-event_datetime', '-id'],
                'indexes': [models.Index(fields=['invoice_number', '-event_datetime'], name='api_oneceve_invoice_d67296_idx'), models.Index(fields=['instrument_key', '-event_datetime'], name='api_oneceve_instrum_137a75_idx'), models.Index(fields=['status_code', '-event_datetime'], name='api_oneceve_status__78dcd0_idx'), models.Index(fields=['is_own_lab', '-event_datetime'], name='api_oneceve_is_own__215994_idx')],
            },
        ),
    ]
